name: Generate demo on Github Pages

on:
  push:
    branches:
     - master
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name ZeegCL
        git config user.email hello.zeegcl@gmail.com
        git fetch --depth=1 origin gh-pages
        git checkout gh-pages
        git rebase --force --autostash master
    - name: Use NodeJS 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm install
    - run: npm run production
    - run: |
        git add --force docs
        git diff --quiet && git diff --staged --quiet || git commit -m "[Actions] Update gh-pages"
        git push origin gh-pages
